local h = fs.open("/.bman/pass/side", "r")
local side = h.readAll()
h.close()
term.setTextColor(colors.green)
term.setBackgroundColor(colors.gray)
term.setCursorPos(1, 19)
term.write("DOOR OPEN")
redstone.setOutput(side, true)
sleep(5)
redstone.setOutput(side, false)
sleep(.5)
os.reboot()